### ISSUE TITLE
UDP Connect Timeout

### ISSUE THREAD

**Issue by Haeldeus** [Mellich/JukePi#20]
Is it possible to add a timeout at UDP Connect? When missclicking on UDP Connect Button i always have to restart my Client, because when there is no possibility to connect by UDP, the Client freezes due to the blocked Thread.

**Comment by Mellich** [comment]
If you want to cancel the udp connect, put it in a own thread and interrupt the thread to stop waiting.
I will add a New Method with a timeout parameter later, but it is not recommended to use this without a thread because the GUI will freeze still until the timeout.

**Comment by Haeldeus** [comment]
Alright, fixed the GUI with the last Commit.
