### ISSUE TITLE
getCurrentTrackURL()

### ISSUE THREAD

**Issue by Haeldeus** [Mellich/JukePi#25]
Maybe a Method like this in the Network Project could be helpful, since you can't get the current Track as a Song but only as a String-value of his title. For the Android Client the URL could be needed for consistency.

**Comment by Mellich** [comment]
url can be found in Song class... can this issue be closed?

**Comment by Haeldeus** [comment]
It may be contained in the Song Class, but you can't get the current Track as an instance of Song, but just its title as a String. So either a Method like getCurrentTrack() or getCurrentTrackURL() would "fix" this problem.
Also, since it's not saved, whether the Song came from the Wishlist or the Gaplist, you can't use gaplist[gaplist.length-1] as an opportunity to get the current Song.

**Comment by Haeldeus** [comment]
Closed, because added with the new features in the Network-Interface
