### ISSUE TITLE
New Functions?

### ISSUE THREAD

**Issue by Haeldeus** [Mellich/JukePi#27]
I have a few Suggestions for new Functions:

1. : Removing all Votes as a possibility for the Admin-Client. Could be used as a Debug-Tool or as a restriction.

2. : Restricting the maximum amount of Admin-Clients per Server. Could be implemented as a Password, that has to be set, when creating a new Server and has to be entered everytime, a Admin wants to connect to the Server. If the password is wrong, either you will be connected as a "Standard"-Client or you have to try again.

3. : Just something i imagined, maybe we should implement a possibility to restrict additions to the Wishlist. Maybe with a Client, that is only allowed to Vote, but not to add Tracks on his own. Could also be implemented Server-Side with a function, that checks if the Client, that wants to add, is an Admin-Client, which are allowed to add or not. This would reduce too much variety between each Song, e.g.: Song A: Irish Folklore, Song B: Speed-Metal, Song C: Speedcore-Techno...

**Comment by Mellich** [comment]
added new permission system to server and network interface.
more different permissions may be added

**Comment by Mellich** [comment]
implemented feature 2

**Comment by Mellich** [comment]
all discussed features are implemented with cde608adc246a18523ac17666a26ea47036dd256. Only client side is missing, then this issue can be closed!

**Comment by Haeldeus** [comment]
I guess all Features are implemented as of now. Close and finish that darn milestone? y/n/m
