### ISSUE TITLE
Gaplist Window is freezing

### ISSUE THREAD

**Issue by Mellich** [Mellich/JukePi#29]
The gaplist window of the client freezes and never handles an update sent by the server

**Comment by Haeldeus** [comment]
As far as my testing goes, the error has to be serversided, as the Client doesn't receive a onGapListUpdatedNotify(). Maybe a bug with the Version-Number? Afaik, the Client implements a lower Interface version at the moment. Maybe this causes a Problem for the Server.

**Comment by Haeldeus** [comment]
The Bug is in the Network-Interface, as you can't add permissions after connecting to the Server. Right now it's working, but not in a performance-optimized manner. Might have to be fixed in future updates to the Network-Interface.

**Comment by Mellich** [comment]
opened new issue for this bug (#31).
closing this issue, if this bug is solved after solving issue #31.

**Comment by Mellich** [comment]
bug is solved partly. The bug appeared, because in the constructor of MainWindow the permissions where requested AFTER requesting the notifications. Thus the notification requests where correctly rejected by the server. In general it is strongly recommended to request the necessary permissions right after the connect to avoid this behavior.
Furthermore, the gap list is still buggy and freezes temporarily, but the main issue might be solved. Leaving this issue open, because it would be nice if this performance weakness could be solved.

**Comment by Haeldeus** [comment]
The freezing is a thing, since either the response from the server takes so long, or sending the information to it. Eventhough, sometimes the Pane is invisible for a few seconds, but I haven't found the reason for this yet.

**Comment by Haeldeus** [comment]
I have just tested this a little bit more and the Pane is created within 15-50 ms, but it isn't shown right after being created, but I don't see the reason for this. Will look further into it.

**Comment by Haeldeus** [comment]
It seems to be the Problem, that there are a lot of processing tasks inside the Swing Thread, so that the UI Update is delayed. Don't know how to fix this right now. Have to leave this issue open until I understand, how WorkerThreads work and how I can bring those into the Client.
