### ISSUE TITLE
GaplistPane Cells aren't painted in their Parser-Color anymore

### ISSUE THREAD

**Issue by Haeldeus** [Mellich/JukePi#33]
The Cells in the Table in the GaplistPane aren't painted anymore in the Colors respective to their Parse-Status. This is just a Reminder for me, to fix this Problem after implementing the Worker Threads for the other Panes.

**Comment by Mellich** [comment]
fixed in 02eaaac2bcbcd53fde0397b0e6a2c2ba23cd6eac even for wishlist
