### ISSUE TITLE
Gaplist window overlapping

### ISSUE THREAD

**Issue by Mellich** [Mellich/JukePi#34]
By adding a new track to the gap list a new, updated gap list shows up, but after a few seconds the old gap list without the added track shows up again and covers the new gap list. Looks like you have to delete the old gap list from the view.

**Comment by Mellich** [comment]
switch to Milestone 1, because this is only a stability issue and has nothing to do with the new feature implementation.

**Comment by Haeldeus** [comment]
As referenced earlier, this should be fixed. Testing required to close this one.

**Comment by Haeldeus** [comment]
Fixed as of now
